"2.8.x/debian/enterprise/package": "Missing Cloudsmith package"
"3.0.x/rhel/oss/package": "Cloudsmith package contains OS version"
"3.0.x/rhel/enterprise/package": "Cloudsmith package contains OS version"
"3.1.x/rhel/oss/package": "Cloudsmith package contains OS version"
