"2.6.x/debian/enterprise/repository": "Missing Cloudsmith package"
"2.8.x/ubuntu/enterprise/package": "Cloudsmith package contains OS version"
"2.8.x/debian/enterprise/package": "Cloudsmith package contains OS version"
"2.8.x/ubuntu/oss/package": "Missing Cloudsmith package (ubuntu/jammy)"
"2.8.x/ubuntu/oss/repository": "Missing Cloudsmith package (ubuntu/jammy)"
"2.8.x/ubuntu/enterprise/repository": "Missing Cloudsmith package (ubuntu/jammy)"
"3.0.x/rhel/oss/package": "Cloudsmith package contains OS version"
"3.0.x/rhel/enterprise/package": "Cloudsmith package contains OS version"
"3.0.x/ubuntu/oss/repository": "Missing Cloudsmith package (ubuntu/jammy)"
"3.0.x/ubuntu/enterprise/repository": "Missing Cloudsmith package (ubuntu/jammy)"
"3.1.x/rhel/oss/package": "Cloudsmith package contains OS version"
