- match: "3\\..*"
  distros:
    - ubuntu
    - rhel
  outputs:
    enterprise: "Kong Enterprise {{ version }}"
    oss: "{{ version }}"
- match: "2\\..*"
  distros:
    - ubuntu
    - rhel
  outputs:
    enterprise: "Kong Enterprise {{ version }}"
    oss: "{{ version }}"
